name: Update dailynews

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 22 * * *'  # 北京时间 06:00
    - cron: '0 10 * * *'  # 北京时间 18:00

jobs:
  build:
    name: mistyspruce
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # concurrency可在workflow级别和job级别配置，分别配置不同job实例之间的并发与相同job实例间的并发
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false # 如果有job在运行，则新job放入队列等待（仅能放入一个，多个使用queue配置）
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Update README Date
        run: |
          DATE=$(date -d "yesterday" +"%Y-%m-%d")
          sed -i -E "s|Daily News\([0-9]{4}-[0-9]{2}-[0-9]{2}\)|Daily News(${DATE})|" README.md
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          chmod +x install.sh
          ./install.sh

      - name: Get articles
        run: python main.py

      - name: Commit
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name dawningnow
          git add archive today.md today_false.md README.md
          git commit -m "Daily News(`date +'%Y-%m-%d'`)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}